export interface GalleryImage {
  src: string;
  alt: string;
  cats: string[];
  rotate?: boolean;
  rotateCCW?: boolean;
  rotateMobile?: boolean;
}

export const inspirationImages: GalleryImage[] = [
  { src: "/images/Lerstien/Frederikshavn-lerstien-terrasse-byview.webp", alt: "Arkitekttegnet udsigtsvilla med stor træterrasse og byudsigt over Frederikshavn — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Torndalsvej/Hals-Torndalsvej-terrasse.webp", alt: "Træterrasse ved moderne, arkitekttegnet sommerhus i Hals — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'udendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-efter-2.webp", alt: "Totalrenoveret og moderniseret 50'er villa i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-stur.webp", alt: "Lys stue i totalrenoveret ejerlejlighed i Reberbansgade, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Karetmagervej/Sæby-ny-villa-funkis-haveside.webp", alt: "Haveside på moderne arkitekttegnet funkisvilla i Sæby — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-terrasse.webp", alt: "Eksklusivt arkitekttegnet sommerhus med pool og træterrasse i Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'udendørs'] },
  { src: "/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø.webp", alt: "Moderne kontorbyggeri og erhvervsbyggeri på Assensvej i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Gjøl/Gjøl-ny-villa-have.webp", alt: "Nybygget arkitekttegnet villa med flot have på Gjøl — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Harald Jensens Vej/Løkken-sommerhus-Haraldjensensvej-terrasse.webp", alt: "Moderne træterrasse ved nyopført arkitekttegnet sommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'udendørs'] },
  { src: "/images/Leonoravej villa tilbygning/Leonoravej-villa-tilbygning-bagside.webp", alt: "Haveside af moderne tilbygning til klassisk villa i Hasseris, Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-køkken.webp", alt: "Nyt arkitekttegnet køkken i renoveret lejlighed på Ågade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Hanebjælken/Vestbjerg-Hanebjælken-ny-villa-haveside.webp", alt: "Arkitekttegnet villa med ensidig taghældning og store vinduespartier i Vestbjerg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Løkken sommerhus/Løkken-Alexandravej-sommerhus-terrasse.webp", alt: "Hyggelig træterrasse ved arkitekttegnet sommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'udendørs'] },
  { src: "/images/Fabrik Aarhus/Aarhus-fabrik-ombygget-køkken-og-altan.webp", alt: "Moderne køkken og altan i totalrenoveret, ombygget fabriksbygning i Aarhus — Arkitekttegnestuen Yderskov", cats: ['indendørs', 'udendørs'] },
  { src: "/images/Gartnerhaven/Hjørring-garnterhaven-ny-villa.webp", alt: "Nyopført arkitekttegnet murstensvilla i Gartnerhaven, Hjørring — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-50m2-Sommerhus.webp", alt: "Arkitekttegnet skitseforslag til kompakt 50m² sommerhus — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'skitser'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-pool.webp", alt: "Indendørs swimmingpool i arkitekttegnet luksussommerhus i Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Gravenstenvej/Aalborg-gravenstenvej-renovering-haveside.webp", alt: "Moderniseret 70'er villa med ny haveside i Hasseris, Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-køkken.webp", alt: "Stilrent hvidt køkken i renoveret lejlighed i Reberbansgade, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Ikarosvej/Aalborg-Ikarosvej-ny-villa-indkørsel.webp", alt: "Nyopført arkitekttegnet funkisvilla med fladt tag og carport i Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Torndalsvej/Hals-Torndalsvej-indgang.webp", alt: "Indgangsparti med træbeklædning på arkitekttegnet sommerhus i Hals — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs', 'udendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-Blokhus.webp", alt: "Arkitekttegnet skitseforslag til moderne sommerhus i Blokhus — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'skitser'] },
  { src: "/images/Emils hus Olufsgade/Brønderslev-olufsgade-efter-vejside.webp", alt: "Ombygning og modernisering af klassisk parcelhus, set fra vejsiden i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Bed and breakfast/Aalborg-bed-and-breakfast.webp", alt: "Renovering og indretning af Bed and Breakfast i Aalborg — Arkitekttegnestuen Yderskov", cats: ['udendørs'] },
  { src: "/images/Lerstien/Frederikshavn-lerstien-terrasse.webp", alt: "Stor flisebelagt terrasse på arkitekttegnet udsigtsvilla i Frederikshavn — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-bad.webp", alt: "Nyt moderne badeværelse med microcement i lejlighedsrenovering på Ågade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Harald Jensens Vej/Løkken-sommerhus-Haraldjensensvej-indkørsel.webp", alt: "Indkørsel og facade på nybygget arkitekttegnet træsommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'udendørs'] },
  { src: "/images/Hals Rækkehuse/Hals-Aalborgvej40-udlejning-.webp", alt: "Moderne rækkehuse og udlejningsboliger tegnet af arkitekt i Hals — Arkitekttegnestuen Yderskov", cats: ['udendørs'] },
  { src: "/images/Højgården/Vestsbjerg-ny-funkisvilla-haveside.webp", alt: "Arkitekttegnet funkisvilla med store vinduespartier mod haven i Vestbjerg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-soveværelse.webp", alt: "Soveværelse med radiatorskjuler i renoveret lejlighed, Reberbansgade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Løkken sommerhus/Løkken-Alexandravej-sommerhus-indgangsparti.webp", alt: "Indgangsparti med glasdør ved arkitekttegnet sommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs', 'udendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-efter-4.webp", alt: "Facade på moderniseret 50'er villa med træbeklædning i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø-glasvæg.webp", alt: "Indendørs glasvægge og mødelokale i moderne erhvervsbyggeri, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/villa sæby/Sæby-ny-villa-kinesisk-tag-haveside.webp", alt: "Unik arkitekttegnet villa med kinesisk inspireret tagform i Sæby — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-køkken.webp", alt: "Køkken med kogeø i eksklusivt sommerhus med pool, Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Neptunvej/Aalborg-neptunvej-tilbygning-terrasse.webp", alt: "Ny træterrasse og tilbygning til parcelhus i Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Emils hus Olufsgade/Brønderslev-olufsgade-efter-indkørsel.webp", alt: "Renoveret parcelhus med ny indkørsel og garage i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-badmiljø.webp", alt: "Moderne badeværelsesmiljø med store fliser i Reberbansgade, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Gjøl/Gjøl-ny-villa-gavl.webp", alt: "Gavl og tagterrasse på nybygget arkitekttegnet villa på Gjøl — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Torndalsvej/Hals-Torndalsvej-køkken.webp", alt: "Køkken med træfronter i arkitekttegnet sommerhus i Hals — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Gartnerhaven/Hjørring-gartnehaven-ny-villa-haveside.webp", alt: "Haveside på klassisk arkitekttegnet villa i Hjørring — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Hanebjælken/Vestbjerg-Hanebjælken-ny-villa-overdækket-terrasse.webp", alt: "Overdækket terrasse på moderne arkitekttegnet villa i Vestbjerg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Fabrik Aarhus/Aarhus-fabrik-ombygget-lejligheder.webp", alt: "Gammel fabrik ombygget til moderne lejligheder i Aarhus — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-vinduer.webp", alt: "Restaurerede klassiske vinduer i lejlighedsrenovering, Ågade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Lerstien/Frederikshavn-lerstien-vejside.webp", alt: "Facade mod vejsiden af moderne arkitekttegnet villa i Frederikshavn — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Leonoravej villa tilbygning/Leonoravej-villa-tilbygning-terrasse.webp", alt: "Træterrasse ved villa med moderne tilbygning i Hasseris, Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1tv-køkken-.webp", alt: "Lyst køkken i totalrenoveret lejlighed i Reberbansgade, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Strandkanten/Sæby-strandkanten-ny-funkisvilla.webp", alt: "Nyopført arkitekttegnet funkisvilla på Strandkanten i Sæby — Arkitekttegnestuen Yderskov", cats: ['villaer'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-aktivitetsrum.webp", alt: "Stort aktivitetsrum i luksussommerhus med pool, Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-efter-køkken.webp", alt: "Moderne lyst køkken efter renovering af parcelhus i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'indendørs'] },
  { src: "/images/Gravenstenvej/Aalborg-gravenstenvej-renovering-vejside.webp", alt: "Ombygget og energioptimeret 70'er villa i Hasseris, Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-Hou.webp", alt: "Arkitekttegnet skitseforslag til ny villa i Hou — Arkitekttegnestuen Yderskov", cats: ['villaer', 'skitser'] },
  { src: "/images/Hals Rækkehuse/Hals-Aalborgvej20-udlejning-indgangsparti.webp", alt: "Indgangsparti til moderne lejelejligheder og rækkehuse i Hals — Arkitekttegnestuen Yderskov", cats: ['indendørs', 'udendørs'] },
  { src: "/images/Karetmagervej/Sæby-ny-villa-funkis-vejside.webp", alt: "Moderne funkisvilla set fra vejsiden i Sæby — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-Loekken.webp", alt: "Arkitekttegnet skitseforslag til sommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'skitser'] },
  { src: "/images/Torndalsvej/Hals-Torndalsvej-stue.webp", alt: "Stue med store vinduespartier i arkitekttegnet sommerhus i Hals — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-soveværelse.webp", alt: "Soveværelse med sildebensparket i renoveret lejlighed, Ågade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Bed and breakfast/Aalborg-bed-and-breakfast-køkken.webp", alt: "Nyt gæstekøkken i Bed and Breakfast i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Højgården/Vestsbjerg-ny-funkisvilla-indgangsparti.webp", alt: "Flot indgangsparti på nyopført funkisvilla i Vestbjerg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'indendørs', 'udendørs'] },
  { src: "/images/Harald Jensens Vej/Løkken-sommerhus-Haraldjensensvej--udebruser.webp", alt: "Praktisk udendørs bruser ved arkitekttegnet sommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-køkken-kogesektion.webp", alt: "Detalje af kogesektion i moderne køkken, Reberbansgade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Emils hus Olufsgade/Brønderslev-olufsgade-efter-bagside.webp", alt: "Bagsiden af parcelhus efter arkitekttegnet ombygning i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/villa sæby/Sæby-ny-villa-kinesisk-tag-vejside.webp", alt: "Arkitekttegnet villa med kinesisk tagform set fra vejen, Sæby — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Neptunvej/Aalborg-neptunvej-tilbygning-terrasse-og-plæne.webp", alt: "Flot træterrasse og have i forbindelse med tilbygning i Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-køkken-spise-plads-alkove.webp", alt: "Alrum med spiseplads, køkken og hyggelig alkove i poolhus, Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Gartnerhaven/Hjørring-gartnerhaven-indkørsel.webp", alt: "Indkørsel og muret gavl på klassisk villa i Hjørring — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-foer-1.webp", alt: "Gammel 50'er villa før totalrenovering og modernisering, Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-køkkenbordplads.webp", alt: "Køkkenbordplads og stænkpanel i renoveret lejlighed, Ågade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Hanebjælken/Vestbjerg-Hanebjælken-ny-villa-værelsesfløj.webp", alt: "Moderne værelsesfløj i arkitekttegnet villa i Vestbjerg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'indendørs'] },
  { src: "/images/Gjøl/Gjøl-ny-villa-indkørsel.webp", alt: "Indkørsel og garage til nybygget arkitekttegnet villa på Gjøl — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1tv-køkkenhylder.webp", alt: "Snedkererede køkkenhylder i renoveret lejlighed, Reberbansgade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Leonoravej villa tilbygning/Leonoravej-villa-tilbygning-vindue.webp", alt: "Stort vinduesparti i ny tilbygning til klassisk villa i Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'indendørs'] },
  { src: "/images/Fabrik Aarhus/Aarhus-fabrik-ombygget.webp", alt: "Gammel fabriksbygning ombygget til erhverv og lejligheder i Aarhus — Arkitekttegnestuen Yderskov", cats: ['udendørs'] },
  { src: "/images/Løkken sommerhus/Løkken-Alexandravej-sommerhus-sidebygning.webp", alt: "Sidebygning med gæsteanneks til arkitekttegnet sommerhus i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse'] },
  { src: "/images/Gravenstenvej/Aalborg-gravenstenvej-renovering-terrassearbejde.webp", alt: "Etablering af ny træterrasse ved renovering af villa i Hasseris, Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Emils hus Olufsgade/Brønderslev-olufsgade-efter-forhave.webp", alt: "Flot anlagt forhave efter modernisering af parcelhus i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-gang.webp", alt: "Lys gang med originale detaljer under renovering, Ågade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Bed and breakfast/Aalborg-bed-and-breakfast-spiseområde.webp", alt: "Spiseområde til gæster i hyggelig Bed and Breakfast i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Højgården/Vestsbjerg-ny-funkisvilla-vejside.webp", alt: "Modernistisk funkisvilla set fra vejen i Vestbjerg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-efter-1.webp", alt: "Indgangsparti til moderniseret 50'er villa i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'indendørs', 'udendørs'] },
  { src: "/images/Neptunvej/Aalborg-neptunvej-tilbygning.haveside.webp", alt: "Haveside af moderne tilbygning til parcelhus i Aalborg — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-toilet.webp", alt: "Moderniseret gæstetoilet med microcement, Reberbansgade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/villa sæby/Sæby-ny-villa-kinesisk-tag-haveside-2.webp", alt: "Haveside af arkitekttegnet villa med kinesisk inspireret tag, Sæby — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Hals Rækkehuse/Hals-Aalborgvej30-udlejning-.webp", alt: "Nybyggede udlejningsboliger tegnet af arkitekt i Hals — Arkitekttegnestuen Yderskov", cats: ['udendørs'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-badmiljø.webp", alt: "Badeværelse med bruser i luksussommerhus med pool, Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-foer-4.webp", alt: "Parcelhus fra 1950'erne før renovering og ombygning, Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer'] },
  { src: "/images/Emils hus Olufsgade/Brønderslev-olufsgade-efter-haveside.webp", alt: "Haveside af moderniseret og udvidet parcelhus i Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø-kontor.webp", alt: "Lyst kontorlokale i nyopført erhvervsbyggeri på Assensvej i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-Loekken-fladt-tag.webp", alt: "Arkitekttegnet skitseforslag til sommerhus med fladt tag i Løkken — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'skitser'] },
  { src: "/images/Gartnerhaven/Hjørring-gartnerhaven-ny-villa-gårdmiljø.webp", alt: "Flisebelagt gårdmiljø ved nyopført villa i Hjørring — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-køkken-undervejs.webp", alt: "Montering af nyt elementkøkken under lejlighedsrenovering i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-efter-3.webp", alt: "Moderniseret 50'er villa set fra haven efter renovering, Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-stuegulv.webp", alt: "Sildebensgulv i renoveret stue, Reberbansgade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Vestvej/Grønhøj-Vestvej-sommerhus-indkørsel.webp", alt: "Indkørsel til moderne arkitekttegnet træsommerhus i Grønhøj — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'udendørs'] },
  { src: "/images/Emils hus Olufsgade/Brønderslev-olufsgade-foer-vejside.webp", alt: "Gammelt parcelhus i Brønderslev før arkitekttegnet ombygning — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Løvevej/Ålbæk-poolhus-toilet.webp", alt: "Badeværelsesmiljø i arkitekttegnet sommerhus med pool, Ålbæk — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'indendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-foer-2.webp", alt: "Parcelhus fra 1950'erne før modernisering, bagside, Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-niche-amerikanerkøleskab.webp", alt: "Specialbygget niche til amerikanerkøleskab i renoveret lejlighed, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-Loekken-syd.webp", alt: "Skitseforslag til nyt sommerhus i Løkken Syd — Arkitekttegnestuen Yderskov", cats: ['sommerhuse', 'skitser'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-stue-soveværelseskik.webp", alt: "Kik fra stue til soveværelse i renoveret lejlighed, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Godthåbsvej/Brønderslev-ombygning-foer-3.webp", alt: "Parcelhus før totalrenovering set fra haven, Brønderslev — Arkitekttegnestuen Yderskov", cats: ['villaer', 'udendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-soveværelse-stuekik.webp", alt: "Kik fra soveværelse mod lys stue i ejerlejlighed, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1th-køkkengulv.webp", alt: "Nyt gulv og indretning i renoveret køkken i Reberbansgade, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Ågade 25/Aalborg-Ågade-renovering-køkken-indpakket.webp", alt: "Nyt køkken under montering i ejerlejlighed på Ågade, Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Reberbansgade/Aalborg-reberbansgade-renovering-1tv-toilet.webp", alt: "Totalrenoveret badeværelse i lejlighed, Reberbansgade i Aalborg — Arkitekttegnestuen Yderskov", cats: ['indendørs'] },
  { src: "/images/Skitseforslag/Skitseforslag-om-og-tilbygning-Brovst.webp", alt: "Arkitekttegnet skitseforslag til stor om- og tilbygning i Brovst — Arkitekttegnestuen Yderskov", cats: ['villaer', 'skitser'] },
];
